import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs';

/** A pending by-name invite: armed by `/dap invite <name>` for a user not
 *  yet on the hub; delivered automatically when that name comes online. */
export interface PendingInvite {
  name: string;
  channel: string;
}

/** Optional persisted settings: ~/.dap/config.json (all fields optional). */
export interface DapFileConfig {
  url?: string;
  name?: string;
  keyPath?: string;
  channelsFile?: string;
  /** Default rooms: ensured (keygen if unknown) and auto-joined after connect. */
  channels?: string[];
  /** Hub-issued client secret (enrollment); the master secret is never persisted. */
  clientSecret?: string;
  /** Armed invite-by-name entries; removed once delivered. */
  invites?: PendingInvite[];
}

export const DEFAULT_URL = 'ws://127.0.0.1:8787/ws';

export const optStr = (v: unknown): string | undefined => (typeof v === 'string' && v.length > 0 ? v : undefined);

/** Read ~/.dap/config.json; a missing or invalid file counts as absent.
 *  `invites` is normalized to [] (files written before the key lack it). */
export function readDapConfig(file = optStr(process.env.DAP_CONFIG_FILE) ?? path.join(os.homedir(), '.dap', 'config.json')): DapFileConfig {
  try {
    const cfg = JSON.parse(fs.readFileSync(file, 'utf8')) as DapFileConfig;
    return { ...cfg, invites: Array.isArray(cfg.invites) ? cfg.invites : [] };
  } catch {
    return { invites: [] };
  }
}

/** Merge `update` into ~/.dap/config.json (read-modify-write, mkdir on
 *  demand): dap_connect persists host/name/default-rooms so the next
 *  launch auto-connects with the same identity. `invites` is the
 *  authoritative list — delivered entries are removed by the caller. */
export function persistDapConfig(
  update: {
    url?: string;
    name?: string;
    channels?: string[];
    invites?: PendingInvite[];
    /** A string upserts; null deletes the key (stale-secret wipe). */
    clientSecret?: string | null;
  },
  file = optStr(process.env.DAP_CONFIG_FILE) ?? path.join(os.homedir(), '.dap', 'config.json'),
): void {
  const cur = readDapConfig(file);
  const next: DapFileConfig = { ...cur };
  if (update.url) next.url = update.url;
  if (update.name) next.name = update.name;
  if (update.channels?.length) {
    next.channels = [...new Set([...(cur.channels ?? []), ...update.channels])];
  }
  if (update.invites) next.invites = update.invites;
  if (update.clientSecret) next.clientSecret = update.clientSecret;
  else if (update.clientSecret === null) delete next.clientSecret;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(next, null, 2) + '\n', { mode: 0o600 });
}

export interface SettingsOverrides {
  url?: string;
  keyPath?: string;
  name?: string;
  channelsFile?: string;
  clientSecret?: string;
}

export interface DapSettings {
  url: string;
  keyPath: string;
  name?: string;
  channelsFile: string;
  clientSecret?: string;
  /** Where clientSecret came from: 'env' (DAP_CLIENT_SECRET or explicit
   *  override — user intent) | 'config' (persisted cache) | undefined. */
  clientSecretSource?: ClientSecretSource;
}

/** Provenance of a resolved clientSecret: 'env' = DAP_CLIENT_SECRET or an
 *  explicit override (user intent — never eligible for the stale-cache
 *  wipe); 'config' = persisted ~/.dap/config.json cache (a hub 401 may
 *  recover it via one enroll-mode re-enroll). */
export type ClientSecretSource = 'env' | 'config';

/** Default identity file is derived from the agent name (or hostname):
 *  ~/.dap/keys/<name>.key — auto-generated by loadOrCreateKeys, so a second
 *  agent on the same machine needs nothing but DAP_AGENT_NAME to get its own
 *  identity. Different machines get different files via hostname. */
export function defaultKeyPath(name: string | undefined): string {
  const who = (name ?? os.hostname()).replace(/[^a-zA-Z0-9._-]/g, '_');
  return path.join(os.homedir(), '.dap', 'keys', `${who}.key`);
}

/** Precedence: explicit override > env var > ~/.dap/config.json > defaults.
 *  channelsFile defaults to ~/.dap/channels.json so no env is needed at all. */
export function resolveDapSettings(overrides: SettingsOverrides = {}): DapSettings {
  const home = os.homedir();
  const file = readDapConfig();
  const name = overrides.name ?? optStr(process.env.DAP_AGENT_NAME) ?? file.name;
  // DAP_CLIENT_SECRET env beats the persisted clientSecret (same chain as url/name);
  // the winner's provenance drives stale-cache recovery on a hub 401.
  const explicitSecret = overrides.clientSecret ?? optStr(process.env.DAP_CLIENT_SECRET);
  const clientSecret = explicitSecret ?? file.clientSecret;
  return {
    url: overrides.url ?? optStr(process.env.DAP_HUB_URL) ?? file.url ?? DEFAULT_URL,
    name,
    keyPath:
      overrides.keyPath ?? optStr(process.env.DAP_KEY_PATH) ?? file.keyPath ?? defaultKeyPath(name),
    channelsFile:
      overrides.channelsFile ??
      optStr(process.env.DAP_CHANNELS_FILE) ??
      file.channelsFile ??
      path.join(home, '.dap', 'channels.json'),
    clientSecret,
    clientSecretSource:
      explicitSecret !== undefined ? 'env' : clientSecret === undefined ? undefined : 'config',
  };
}
